name: 'Terraform'

on:
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform fmt
      uses: hashicorp/setup-terraform@v2
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      uses: hashicorp/setup-terraform@v2
      id: init
      run: terraform init
      
    - name: Terraform Validate
      uses: hashicorp/setup-terraform@v2
      id: validate
      run: terraform validate