name: Terrform

on:
  push:
    branches: [ "justin-lf-patch-1" ]
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
steps:
- uses: actions/checkout@v3
- uses: hashicorp/setup-terraform@v2

- name: Terraform fmt
  id: fmt
  run: terraform fmt -check
  continue-on-error: true

- name: Terraform Validate
  id: validate
  run: terraform validate -no-color
