on:
  push:
    branches: [ "justin-lf-patch-1" ]
  pull_request:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
jobs:
  terraform:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate

