name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:

  test_self_hosted:
    name: Testing self-hosted tag
    runs-on: self-hosted
    steps:
      - name: step 1
        run: echo "Hello World!"
